/**
 * Validation heuristics for Google Maps place entities and coordinates.
 * Filters out internal Google protobuf tags, telemetry, aspect ratios,
 * busyness labels, hours, and non-place DOM artifacts.
 */

import { isValidCoordinate } from './coordinates';

/**
 * Validates that latitude and longitude represent a realistic geographic location on Earth,
 * rejecting protobuf enums (pure integers like [6, 7], [1, 2], [81, 84]), null-island offsets, and zeroes.
 */
export function isPlausibleGeoCoordinate(latitude: number, longitude: number): boolean {
  if (!isValidCoordinate(latitude, longitude)) return false;

  // 1. Reject if either coordinate is an exact integer (e.g. [3, -58.4386], [6, 7], [1, 2], [81, 84], [4.6, 126])
  // Genuine Google Maps place pin coordinates always have fractional decimal digits (e.g. -34.602448).
  // Integer numbers in protobuf arrays represent enums, photo counts, review counts, status codes, or ratios.
  if (Number.isInteger(latitude) || Number.isInteger(longitude)) {
    return false;
  }

  // 2. Reject Near-Zero / Null Island offsets (e.g. 0.0001166, 0.0000186)
  if (Math.abs(latitude) < 0.1 && Math.abs(longitude) < 0.1) {
    return false;
  }

  // 3. Reject if either coordinate is exactly zero while the other is small
  if ((latitude === 0 && Math.abs(longitude) < 1) || (longitude === 0 && Math.abs(latitude) < 1)) {
    return false;
  }

  return true;
}

/**
 * Validates that a string represents a genuine human-readable place title or business name,
 * filtering out internal protobuf identifiers, user account avatars, timestamps, prices, and status enums.
 * Also supports raw coordinate titles generated by Google Maps for dropped pins (e.g. "(-36.495170, -56.691744)").
 */
export function isLegitimatePlaceTitle(title: string | undefined | null): boolean {
  if (!title || typeof title !== 'string') return false;
  const t = title.trim();

  // Length boundaries
  if (t.length < 2 || t.length > 150) return false;

  // Check if title is a coordinate string like:
  // "(-36.495170, -56.691744)", "(40.252596, 58.439703)", "40°15'09.4\"N 58°26'22.9\"E"
  const isCoordTitle =
    /^\(?-?\d{1,3}\.\d+,\s*-?\d{1,3}\.\d+\)?$/.test(t) ||
    /^\d{1,2}°\d{1,2}'[\d\.]+"?[NS]\s+\d{1,3}°\d{1,2}'[\d\.]+"?[EW]$/i.test(t);

  if (isCoordTitle) {
    return true;
  }

  // Must contain at least one letter (not purely numbers or punctuation)
  if (!/[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ]/.test(t)) return false;

  // Reject user account avatar links / sign-out elements
  if (t.toLowerCase().includes('cuenta de google') || t.toLowerCase().includes('google account')) {
    return false;
  }

  // Reject strings containing "||" (Protobuf serialization separators)
  if (t.includes('||')) {
    return false;
  }

  // Exact matches on internal protobuf tokens, photo labels, and UI action triggers
  const exactForbidden = [
    'ugcs_reference',
    'geo_photo_reference',
    'image_alleycat',
    'street view',
    'bizbuilder',
    'launch',
    'foto',
    'fotos',
    'photo',
    'photos',
    'psm',
    'gps',
    'gsm',
    'tipo 2',
    'tomacorriente',
  ];
  if (exactForbidden.includes(t.toLowerCase())) return false;

  // Reject photo count strings like "797 fotos", "2219 fotos", "45 photos"
  if (/^\d+\s*(?:fotos?|photos?)$/i.test(t)) return false;

  // Reject internal Google asset, telemetry, and logging tags
  const forbiddenPrefixes = [
    'photos:',
    'bizbuilder:',
    'bizbuilder',
    'casanova:',
    'SearchResult.',
    '2ahUKE',
    'CAES',
    'CAIS',
    'CAEQ',
    'CAIQ',
    'gcid:',
    'ugcs_',
    'geo_photo',
    'image_alleycat',
  ];
  if (forbiddenPrefixes.some((p) => t.toLowerCase().startsWith(p.toLowerCase()))) {
    return false;
  }

  // Reject URL data parameter patterns like !10m1!1e1 or !3m1!1e3
  if (/^!\d+[a-z]\d+!/i.test(t) || /^\d+[a-z]\d+!/i.test(t)) {
    return false;
  }

  // Reject ISO dates & timestamps (e.g., 2027-01-02, 2015-02-08T08:00:00.000Z, 2026-06-15T05:00:00.000Z)
  if (/^\d{4}-\d{2}-\d{2}(?:T[\d:\.]+Z?)?$/.test(t)) return false;

  // Reject prices (e.g., $ 1.282.963, 150€)
  if (/^[\$€£¥]\s*\d/.test(t) || /^\d+[\.,]\d{2}\s*[\$€£¥]/.test(t)) return false;

  // Reject days of the week
  const days = [
    'lunes', 'martes', 'miércoles', 'miercoles', 'jueves', 'viernes', 'sábado', 'sabado', 'domingo',
    'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday',
  ];
  if (days.includes(t.toLowerCase())) return false;

  // Reject busyness and operational status phrases
  const statusPhrases = [
    'un poco concurrido',
    'poco concurrido',
    'más concurrido de lo habitual',
    'mas concurrido de lo habitual',
    'menos concurrido de lo habitual',
    'máxima concurrencia',
    'maxima concurrencia',
    'habitualmente concurrido',
    'cerrado permanentemente',
    'cerrado temporalmente',
    'cerrado',
    'permanently closed',
    'temporarily closed',
    'closed',
    'abierto las 24 horas',
    'open 24 hours',
    'busy',
    'not busy',
    'desayuno-almuerzo',
  ];
  if (statusPhrases.includes(t.toLowerCase())) return false;

  // Reject timezones (e.g. America/Montevideo, Europe/London, Asia/Tokyo)
  if (/^(America|Europe|Asia|Africa|Pacific|Atlantic|Indian|Antarctica)\/[A-Za-z_]+/.test(t)) {
    return false;
  }

  // Reject time strings (e.g. 12:00, 14:30 PM, 9:00 AM)
  if (/^\d{1,2}:\d{2}(\s*(AM|PM|am|pm))?$/.test(t)) return false;

  // Reject ratings (e.g. 4.5, 4,5 estrellas, 4.8 stars)
  if (/^\d([.,]\d)?\s*(estrellas|stars)?$/i.test(t)) return false;

  // Reject internal Google 8-60 char base64-like photo, feature, or list tokens without spaces
  // (e.g. 5XdUApWbscM, p_Bc38opygI, yfDguqJglQs, d3fCauWaHYnL1sQPjYam8QM, dtwiDbA3kCGXN9zXNogHTRiK3nccSw)
  if (/^[a-zA-Z0-9_-]{8,60}$/.test(t) && !t.includes(' ')) {
    // If it contains digits or underscores/hyphens, it is an internal hash/token, not a real place name
    if (/[\d_-]/.test(t)) {
      return false;
    }
    // If it contains unnatural mixed case (like yfDguqJglQs) and is not a regular capitalized word (e.g. "Singapore", "Vietnam")
    if (/[a-z]/.test(t) && /[A-Z]/.test(t) && !/^[A-Z][a-z]+$/.test(t)) {
      return false;
    }
    // Unconditionally reject any single token >= 20 characters
    if (t.length >= 20) {
      return false;
    }
  }

  // Reject internal Google asset paths and pegman easter eggs (e.g. /tactile/pegman_v3/merman/)
  if (t.includes('/tactile/') || t.toLowerCase().includes('pegman')) {
    return false;
  }

  // Reject scientific notation
  if (/^\d+(\.\d+)?[eE]\+\d+$/.test(t)) return false;

  // Reject URLs or internal paths
  if (
    t.startsWith('http://') ||
    t.startsWith('https://') ||
    t.startsWith('/m/') ||
    t.startsWith('/g/') ||
    t.startsWith('/search') ||
    t.startsWith('/fake_') ||
    t.startsWith('/tactile')
  ) {
    return false;
  }

  return true;
}
